---
# NOT WORKING YET !
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - RELEASE"
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]

###############
# Set the Job #
###############
jobs:

  deploy_release:
    name: Create new package version
    needs: build
    runs-on: ubuntu-latest
    container:
      image: docker://hardisgroupcom/sfdx-hardis:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: |
           sfdx hardis:auth:login --devhub
           sfdx force:package:version:create -p $FFLIB_APEX_MOCKS_PACKAGE_ID --installationkeybypass -w 60


