---
# NOT WORKING YET !
name: Create a Scratch Org, Push Source and Run Apex Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://hardisgroupcom/sfdx-hardis:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Test scratch org creation
        run: |
          echo 'y' | sfdx plugins:install sfdx-hardis && \
          sfdx hardis:auth:login --devhub && \
          sfdx force:config:set defaultdevhubusername=DevHub_FFLib_ApexMocks
          sfdx force:org:create -f config/project-scratch-def.json --setdefaultusername -d 1 && \
          sfdx force:source:push && \
          sfdx force:apex:test:run -w 5 && \
          sfdx force:org:delete -p
        env:
          SFDX_CLIENT_ID_DEVHUB_FFLIB_APEXMOCKS: ${{ secrets.SFDX_CLIENT_ID_DEVHUB_FFLIB_APEXMOCKS }}
